config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :incidents, except: [:destroy] do
    resources :comments, only: [:index, :create], shallow: true
    resources :affecting_pins, only: [:create]
  end

  delete "incidents/:id", to: "incidents#destroy", as: "destroy_incident"

  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  patch "toggle_pin/:id", to: "affecting_pins#toggle_pin", as: "toggle_pin"

end

app/models/affected_pin.rb
class AffectedPin < ApplicationRecord
    belongs_to :user
    belongs_to :incident
  end

app/models/affecting_pin.rb
class AffectingPin < ApplicationRecord
    belongs_to :user
    belongs_to :incident
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :incident
  belongs_to :user

  validates :content, presence: true
end

app/models/incident.rb
class Incident < ApplicationRecord

  belongs_to :user
  has_many :affecting_pins
  has_many :comments, dependent: :destroy
  has_many :users, through: :affecting_pins
  has_many_attached :photos

  validates :location, presence: true
  validates :category, presence: true, inclusion: { in: ['Accident', 'Construction', 'Structural'] }
  validates :description, presence: true
  enum status: { unresolved: false, resolved: true }

  # validates :status, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def has_pins_by_user?(user)
    self.affecting_pins.where(user: user).present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :comments
  has_many :affecting_pins
  has_many :incidents, through: :affecting_pins
  has_many :incidents

  def affecting_incidents
    Incident.joins(:affecting_pins).where(affecting_pins: { user_id: id })
  end
end

app/controllers/affecting_pins_controller.rb
class AffectingPinsController < ApplicationController
  before_action :authenticate_user!

  def toggle_pin
    @incident = Incident.find(params[:id])
    @affecting_pin = @incident.affecting_pins.find_or_initialize_by(user: current_user)

    if @affecting_pin.persisted?
      @affecting_pin.destroy
      @is_affected = false
    else
      @affecting_pin.save
      @is_affected = true
    end

    respond_to do |format|
      format.html { redirect_to incidents_path(last_incident_id: @incident.id) }
      format.js   # Add this line to handle AJAX requests
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @incident = Incident.find(params[:incident_id])
    @comments = @incident.comments
  end

  def create
    @incident = Incident.find(params[:incident_id])
    @comment = @incident.comments.new(comment_params)
    @comment.user = current_user # Assuming you have a current_user method lol

    if @comment.save
      redirect_to incident_comments_path(@incident), notice: 'Comment was successfully created.'
    else
      render 'incidents/comments' # Adjust this path based on your view structure lol
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :img_url) # Include other fields as needed lol
  end

end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController

  def new
    @user_street_address = session[:userStreetAddress]
    @incident = Incident.new
  end

  def create
    @incident = Incident.new(incident_params)
    @incident.user = current_user

    uploaded_files = params[:incident][:photos]
    path = File.join Rails.root, 'public', 'uploads'
    FileUtils.mkdir_p(path) unless File.exist?(path)
    # Save the file to a specific location
      uploaded_files.reject{|f| f == ""}.each do |uploaded_file|
        File.open(File.join(path, uploaded_file.original_filename), 'wb') do |file|
          file.write(uploaded_file.read)
        end
      end

    if @incident.save
      redirect_to dashboard_path, notice: 'Incident was successfully created.'
    else
      render :new
    end
  end

  def show
    @incident = Incident.find(params[:id])
    @markers = [
      {
        lat: @incident.latitude,
        lng: @incident.longitude,
        url: incident_path(@incident),
        marker_html: render_to_string(partial: "marker", locals: { incident: @incident })
      }
    ]
  end

  def index
    puts "Mapbox API Key: #{ENV['MAPBOX_API_KEY']}"
    @incidents = Incident.all
    @today_incidents = incidents_today

    @markers = @incidents.geocoded.map do |incident|
      {
        lat: incident.latitude,
        lng: incident.longitude,
        url: incident_path(incident),
        marker_html: render_to_string(partial: "marker", locals: { incident: incident })
      }
    end
  end

  def destroy
    @incident = Incident.find(params[:id])
    if @incident.user == current_user
      @incident.destroy
      flash[:notice] = "Incident successfully deleted."
      redirect_to dashboard_path
    else
      flash[:alert] = "You are not authorized to delete this incident."
      redirect_to dashboard_path
    end
  end

end

private

def incident_params
  params.require(:incident).permit(:location, :category, :description, :status, photos: [])
end

def incidents_today
  selected_location = [38.709460, -9.128540]
  radius = 10 # in kilometers
  Incident.where("created_at >= ?", Time.zone.now.beginning_of_day)
          .near(selected_location, radius)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]



  def home
  end

  def dashboard
    @affecting_incidents = current_user.affecting_incidents.limit(3)
    @reported_incidents = current_user.incidents.limit(3)
    @incidents = Incident.all
    @markers = @incidents.geocoded.map do |incident|
      {
        lat: incident.latitude,
        lng: incident.longitude,
        url: incident_path(incident),
        marker_html: render_to_string(partial: "marker", locals: { incident: incident })
      }
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_page_class(path)
    'active' if current_page?(path)
  end
end

app/views/comments/index.html.erb
<div class="mt-4 mb-5 pb-5 mx-4">
  <div class="mb-3">
    <%= link_to incidents_path(last_incident_id: @incident.id), class: "back-link" do %>
      <i class="fa-solid fa-chevron-left"></i>
    <% end %>
  </div>
  <h2>Comments</h2>
  <p><%= @comments.count %> comments</p>

  <% @comments.reverse_each do |comment| %>
    <div class="mt-2 p-2" style='margin-left: 20px'>
      <div class="d-flex justify-content-start">
        <% if comment.user.photo.key.nil? %>
          <img src="https://via.placeholder.com/150"
            alt="<%= comment.user.first_name %> profile"
            style="width: 50px; height: 50px; border-radius: 50%; fill: crop; object-fit: cover;">
        <% else %>
          <%= cl_image_tag comment.user.photo.key, style: "width: 50px; height: 50px; border-radius: 50%; object-fit: cover;" %>
        <% end %>
        <div class='mx-3'><strong><%= comment.user.first_name %></strong><strong> <%= comment.user.last_name %></strong></div>
      </div>
      <div class="ms-2 ps-5">
        <div class="d-flex flex-column">
          <div class='d-flex justify-content-end'>
            <p class="text-end"><%= comment.content %></p>
            <% if comment.img_url.present? %>
              <img src="<%= comment.img_url %>" alt="Comment image" style="max-width: 200px; height: auto; object-fit: cover;">
            <% end %>
          </div>
          <div class='d-flex justify-content-end'><span><small><%= time_ago_in_words(comment.created_at) %> ago</small></span></div>
        </div>
      </div>
    </div>
  <% end %>
  <%# Form %>
  <div class="mt-3">
    <%= form_with(model: [@incident, Comment.new], local: true) do |form| %>
      <%= form.text_area :content, placeholder: "Your comment here...",
        required: true, style: "border-radius: 8px; border: none; width: 100%; height: 100px;" %><br>

      <small><%= form.label :img_url, "Upload a photo:"%></small>
      <small><%= form.file_field :img_url %></small><br>
      <div class="d-flex justify-content-end mt-4">
        <%= form.submit "Submit",
          style: "border-radius: 8px; border: none; padding: 10px 50px; background-color: #FF7900; color: #fff;" %>
      <% end %>
    </div>
  </div>
</div>

app/views/incidents/_affected_count.html.erb
<p class='m-0' style='color: #FF7900'>
  <em><%= incident.affecting_pins.count %> <%= 'person'.pluralize(incident.affecting_pins.count) %> affected</em>
</p>

app/views/incidents/_incident.html.erb
<div class='offcanvas offcanvas-bottom' tabindex='-1' id='offcanvasBottom-<%= incident.id %>' aria-labelledby='offcanvasBottomLabel'>
  <div class='offcanvas-header'>
  </div>
  <div class='offcanvas-body small mx-3'>
    <div class='d-flex justify-content-between'>
      <!-- People Affected -->
      <p class='m-0' style='color: #FF7900'>
        <em><%= incident.affecting_pins.count %> <%= 'person'.pluralize(incident.affecting_pins.count) %> affected</em>
      </p>
      <!-- Share Button with Options -->
      <div data-controller="share" class='share-options'>
        <div data-action="click->share#toggle" class='share-button' id='shareButton-<%= incident.id %>'>
          <i class='fa-solid fa-share-nodes' style='color: #7b7f83;'></i>
        </div>
        <div class='options-container hidden' data-share-target="options" id='optionsContainer-<%= incident.id %>'>
          <!-- WhatsApp Share Button -->
          <%= link_to "https://api.whatsapp.com/send?text=#{incident_url(incident)}", target: '_blank', title: 'Share on WhatsApp' do %>
            <i class='fab fa-whatsapp'></i>
          <% end %>
          <!-- Copy Link Button -->
          <button id='copyLinkButton-<%= incident.id %>' title='Copy Link'>
            <i class='far fa-copy'></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Title of the incident (category) -->
    <div class='d-flex flex-column'>
      <h2><%= incident.category %></h2>
      <!-- Location -->
      <div>
        <i class='fa-solid fa-location-dot' style='color: #7b7f83;'></i> <%= incident.location %>
      </div>
      <!-- Date -->
      <div>
        <i class="fa-solid fa-calendar-plus"></i>
        Reported on
        <%= incident.created_at.strftime('%d') %>
        <%= incident.created_at.strftime('%B') %>
        <%= incident.created_at.strftime('%Y') %>
      </div>
      <!-- IT AFFECTS ME BTN-->
      <div class='d-flex justify-content-start mt-3'>
        <%= turbo_frame_tag "toggle_button_#{incident.id}" do %>
          <%= simple_form_for incident, remote: true, data: { form: 'toggle-pin' }, url: toggle_pin_path(incident), method: :patch do |f| %>
            <% if incident.has_pins_by_user?(current_user) %>
              <button type='submit' id='toggleButton' class='btn btn-light rounded-4 px-4 py-3 mb-3' style='color: #FF7900'>
                <i class='fa-solid fa-triangle-exclamation' style='color: #FF7900;'></i>
                Doesn't affect
              </button>
            <% else %>
              <button type='submit' id='toggleButton' class='btn btn-primary text-white rounded-4 px-4 py-3 mb-3'>
                <i class='fa-solid fa-triangle-exclamation' style='color: #ffffff;'></i>
                  It affects me
              </button>
            <% end %>
          <% end %>
        <% end%>
        <%= link_to incident_comments_path(incident_id: incident.id) do %>
          <button type='button' class='btn btn-light rounded-4 px-4 py-3' style='margin-left: 10px'>
            <%= incident.comments.count %> <%= 'comment'.pluralize(incident.comments_count) %>
          </button>
        <% end %>
      </div>
    </div>
    <!-- Is it still there? -->
    <p class='mt-0'>Is it still there?
      <button class='option-button btn btn-light rounded-4 py-0' onclick='toggleColor(this)'><small>Yes</small></button>
      <button class='option-button btn btn-light rounded-4 py-0' onclick='toggleColor(this)'><small>No</small></button>
    </p>
    <script>
      function toggleColor(clickedButton) {
        const buttons = document.querySelectorAll('.option-button');
          buttons.forEach(button => {
            if (button === clickedButton) {
            // Toggle color for the clicked button
              button.style.color = button.style.color === 'orange' ? 'black' : 'orange';
              button.style.backgroundColor = button.style.backgroundColor === '#FFE9D6' ? 'black' : '#FFE9D6';
              button.style.border = button.style.border === '1px solid #ddd' ? 'none' : '1px solid #ddd';
            } else {
          // Reset color for the other buttons
              button.style.color = 'black';
              button.style.backgroundColor = 'white';
              button.style.border = '1px solid #ddd';
            }
          });
      }
    </script>
    <p><%= incident.description %></p>
    <!-- Existing code above -->


<!-- Add Bootstrap Carousel for Incident Photos -->
    <div class="d-flex justify-content-center">
        <% if incident.photos.count == 1 %>
          <%= cl_image_tag incident.photos[0].key, height: 150, width: 370, crop: :fill, class: 'd-block mb-1' %>
        <% else %>
          <div id="incidentCarousel" class="carousel slide" data-bs-ride="carousel" style="width: 100%;">
              <div class="carousel-inner">
                <% incident.photos.each_with_index do |photo, index| %>
                  <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
                    <%= cl_image_tag photo.key, height: 150, width: 370, crop: :fill, class: 'd-block mb-1' %>
                  </div>
                <% end %>
              </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#incidentCarousel" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#incidentCarousel" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/incidents/_marker.html.erb
<div type="button"

  id="button-<%= incident.id %>"
  data-bs-toggle="offcanvas"
  data-bs-target="#offcanvasBottom-<%= incident.id %>"
  aria-controls="offcanvasBottom">

  <%= image_tag "icon.png", height: 50, alt: "marker", style: "position: relative; bottom: 25px;" %>

</div>

app/views/incidents/_postition.html.erb
  <%= image_tag "pathguy.png", height: 50, alt: "marker", style: "position: relative; bottom: 25px;" %>

app/views/incidents/_wheelchair.html.erb
<%= image_tag "pathguy.png", height: 30, width: 30, alt: "Logo" %>

app/views/incidents/index.html.erb
  <div id='biglogo' class='logo_overlay d-flex justify-content-center p-4'>
    <%= image_tag 'logo_incidents.png',
    style: 'width: 100%; -webkit-filter: drop-shadow(0 4px 8px rgba(0,0,0,0.1));' %>
  </div>


  <div id='map' style='width: 100%; max-height: calc(100vh - 56px);'
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>


  <div data-controller="open-incidents">
    <% @incidents.each do |incident| %>
      <%= render "incident", incident: incident %>
    <% end %>
  </div>

  <div class="incidents-count" style='margin-top: 515px'>
    <div class="d-flex justify-content-between align-items-center">
      <button type="button"
              class="close btn bg-transparent btn-outline-primary"
              style='border-color: transparent; padding-left: 0;'
              aria-label="Close"
              onclick="closeIncidentsCount()">
        <span aria-hidden="true" style="font-size: 1.5rem;">&times;</span>
      </button>
      <p class='my-0 mx-2'>Today there are <strong><%= @today_incidents.length %> new incidents</strong><br>around you.</p>
    </div>
  </div>


<script>
  function closeIncidentsCount() {
    document.querySelector(".incidents-count").style.display = "none";
  }
</script>

<script>
  document.addEventListener('DOMContentLoaded', (event) => {
    // Assuming you have a way to reference your Stimulus controller here
    controller.getUserLocation();
  });
</script>

app/views/incidents/new.html.erb
<div class='p-4'>
  <div class='d-flex justify-content-center'>
    <div class='d-flex flex-column mt-4'>
      <div class='d-flex justify-content-center mb-3'><%= image_tag 'real_cone.png', style:'width: 60px'%></div>
      <h2 style='color: #FF7900'>Report an Incident</h2>
    </div>
  </div>


    <div class='bg-white rounded-4 p-3 mt-4'>
      <%= form_with(model: @incident, local: true, url: incidents_path) do |form| %>
        <div class="form-group">
          <i class='fa-solid fa-location-dot' style='color: #FF7900;'></i>
          <strong><%= form.label :location, "Where?", style: 'color: #FF7900;' %></strong>

        <%= form.text_field :location, id: "user-location", class: "form-control rounded-4 my-2", required: true %>

        </div>


      <div class="d-flex justify-content-start">
        <%= image_tag 'cone_orange.png',
            style: 'width: 15px; height: 15px',
            class: 'cono' %>
        <strong><p style='color: #FF7900; margin-bottom: 0px'>Which type of incident?<p></strong>
      </div>


      <div class="form-group">
         <%= form.select :category, ['Construction', 'Accident', 'Structural'], { prompt: 'Select Type' }, class: 'form-control rounded-4 my-2' %>
      </div>
      <br>



      <div class="form-group">
        <i class="fa-solid fa-circle-info" style="color: #FF7900;"></i>
        <strong><%= form.label :description, "Tell us more",
                                style: 'color: #FF7900;' %>
        <%= form.text_area :description,
                            class: "form-control rounded-4 my-2",
                            placeholder: "Enter your description here",
                            required: true %></strong>
      </div>
      <br>

      <div class="form-group">
        <i class="fa-solid fa-image" style="color: #FF7900;"></i>
        <strong><%= form.label :photos, "Add photos", style: 'color: #FF7900;', class: 'mb-2' %>
        </strong>
        <small><%= form.file_field :photos, :multiple => true, class: "form-control-file", style: 'color: #7B7F83' %></small>
      </div>

      <div class="d-flex justify-content-end mt-4">
        <%= form.submit "Submit",
                        style: "border-radius: 8px; border: none; padding: 10px 50px; background-color: #FF7900; color: white;" %>
      </div>
    <% end %>
  </div>



  <p style="display:none;" id='user_location_input'><%= params[:location] != nil ? params[:location].strip : "" %></p>
</body>

<script>
  const userLocation = document.getElementById('user-location');
  const loc = document.getElementById('user_location_input').innerText;
  console.log(loc);
  userLocation.value = loc;
</script>

</div>

app/views/incidents/toggle_pin.turbo_stream.erb
<%= turbo_stream.replace "toggle_button_#{incident.id}" do %>
  <%= render partial: 'incidents/toggle_button', locals: { incident: @incident } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PathAndRoll</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

     <!-- Mapbox CSS -->
  <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />

  <!-- Mapbox JS -->
  <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>


  </head>

  <body>
    <%# Line below serves to delete navbar from landing and ragistration pages %>
    <% unless current_page?(root_path) || current_page?(new_user_registration_path) || current_page?(new_user_session_path) %>
    <%= render "shared/navbar" %>
    <% end %>
    <%= yield %>
  </body>

</html>

app/views/pages/_info_window.html.erb
<div>
  <h3><%= incident.location %></h3>
  <h1><%= incident.category %></h1>
  <%= link_to 'View Details', incident_path(incident), target: '_blank' %>
</div>

app/views/pages/_marker.html.erb
<div
  type="button"
  data-bs-toggle="offcanvas"
  data-bs-target="#offcanvasBottom-
  <%= incident.id %>"
  aria-controls="offcanvasBottom">
  <%= image_tag "icon.png", height: 50, alt: "marker", style: "vertical-align: bottom;" %>
</div>

app/views/pages/dashboard.html.erb
<div>
  <div class='m-4 mt-5'>
    <div class="d-flex justify-content-between mx-3">

    <h2>Hi, <%= current_user.first_name %>!</h2>
    <p></p>

      <%= cl_image_tag(@current_user.photo.key, class: 'rounded-circle', width: 50, height: 50, alt: 'User Photo', fill: 'crop', display: 'cover') %>
    </div>

    <div class='mt-4 bg-white rounded-4 p-3'>
      <div class='d-flex justify-content-between'>
        <h3>Incidents Affecting You</h3>
        <a href="<%= incidents_path %>" class="see-all">see all</a>
      </div>

      <%# Loop through incidents affecting the user %>
      <% if @affecting_incidents.present? %>
        <% @affecting_incidents.take(3).each do |incident| %>
          <div class='p-3 rounded-4 my-2 d-flex justify-content-between'
               style="<%= incident.resolved? ? 'background-color: #B1FBE6; color: #0AA374;' : 'background-color: #FFE9D6; color: #FF7900;' %>">
            <div><%= incident.category %></div>
            <div>
              <%= incident.created_at.strftime('%d') %>
              <%= incident.created_at.strftime('%b') %>
              <%= incident.created_at.strftime('%Y') %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p style='color: gray'><em>No incidents to display.</em></p>
      <% end %>
    </div>

    <div class='mt-3 bg-white rounded-4 p-3'>
      <div class='d-flex justify-content-between'>
        <h3>Your Reported Incidents</h3>
        <a href="<%= incidents_path %>" class="see-all">see all</a>
      </div>

      <%# Loop through incidents reported by the user %>
      <% if @reported_incidents.present? %>
        <% @reported_incidents.each do |incident| %>
          <div class='p-3 rounded-4 my-2 d-flex justify-content-between align-items-center'
               style="<%= incident.resolved? ? 'background-color: #B1FBE6; color: #0AA374;' : 'background-color: #FFE9D6; color: #FF7900;' %>">
            <div class="flex-grow-1"><%= incident.category %></div>
            <div class="text-right">
              <%= incident.created_at.strftime('%d %b %Y') %>
              <%= link_to '×', destroy_incident_path(incident),
                  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
                  class: "close btn btn-outline-primary#{incident.resolved? ? ' text-custom-color' : ''}",
                  style: 'border: none' %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p style='color: gray'><em>You haven't reported any incident yet.</em></p>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="landing-page px-4 py-5">
  <div class="d-flex flex-column py-5">
    <%= image_tag 'pathroll_logo.png', style: 'width: 200px; margin-left: 5px;' %>
    <h2 class="pb-2 mx-3">Move safely around your neighborhood!</h2>
    <ul class="pb-2">
      <li class="pb-2">Check any incident in your area</li>
      <li>Report new incidents to help others</li>
    </ul>
    <br>
    <div class="d-flex justify-content-end">
      <%= link_to "Get started", incidents_path, class: "myprimary btn btn-primary btn-lg text-light px-5 mx-3 rounded-4" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-bottom">
  <div class="container-fluid">
    <div class="navbar-nav flex-grow-1">
      <div class="d-flex justify-content-around">
        <%= link_to incidents_path, class: 'nav-link' do %>
          <i class="icons fa-solid fa-house
          <%= 'active' if current_page?(incidents_path) %>"
          style="color: <%= '#FF7900' if current_page?(incidents_path) %>;">
          </i>
        <% end %>
        <%= link_to new_incident_path(batata: @batatinha ), class: 'nav-link', id: 'new_incident_address' do %>
          <%= image_tag 'cone.png', class: 'cone p-0' %>
        <% end %>
        <%= link_to dashboard_path, class: 'nav-link' do %>
          <i class="icons fas fa-user <%= 'active' if current_page?(dashboard_path) %>"
          style="color: <%= '#FF7900' if current_page?(dashboard_path) %>;"></i>
        <% end %>
      </div>
    </div>
  </div>
</nav>